import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import {
  IconAlertTriangle,
  IconDrafting,
  IconCheckCircle,
  IconLoader,
} from "../common/Icon";
import type { DrawingStatus } from "../../types/engineering";
import { listAgents, downloadDrawing } from "../../api";
import {
  type DrawingCardInfo,
  type DrawingKind,
  canGenerateSelected,
  cardActionHint,
  isAnyDrawingGenerating,
  toggleDrawing,
} from "../../utils/drawingSelection";
import { AgentPairingPanel } from "./AgentPairingPanel";

interface DrawingViewProps {
  drawingStatus: DrawingStatus;
  drawingError?: string;
  jobId: string;
  module: string;
  shellId: number;
  onGenerate: (agentId?: string, drawings?: DrawingKind[]) => void;
  isTriggering: boolean;
  /**
   * Heat Exchanger jobs: one card per drawing (fabrication + general
   * arrangement), each with its own tick box and one shared "Generate
   * selected drawings" button. Legacy single-drawing jobs omit it.
   */
  cards?: DrawingCardInfo[];
}

export function DrawingView({
  drawingStatus,
  drawingError,
  jobId,
  module,
  shellId,
  onGenerate,
  isTriggering,
  cards,
}: DrawingViewProps) {
  const multi = Boolean(cards);
  const anyGenerating = cards ? isAnyDrawingGenerating(cards.map((c) => c.status)) : drawingStatus === "generating";
  const isGenerating = isTriggering || anyGenerating;
  const [selected, setSelected] = useState<DrawingKind[]>([]);
  const [downloadError, setDownloadError] = useState<string | null>(null);
  const [downloading, setDownloading] = useState<DrawingKind | null>(null);
  const [selectedAgentId, setSelectedAgentId] = useState<string | null>(null);

  const {
    data: agents = [],
    isFetching: isFetchingAgents,
    refetch,
  } = useQuery({
    queryKey: ["agents"],
    queryFn: listAgents,
    // A freshly started agent (or one that just went offline) should show
    // up here on its own - nobody should have to know to press Refresh.
    refetchInterval: 5000,
  });

  const loadAgents = async () => {
    await refetch();
  };

  const onlineAgents = agents.filter((a) => a.online);
  const activeAgentId =
    selectedAgentId && onlineAgents.some((a) => a.agentId === selectedAgentId)
      ? selectedAgentId
      : onlineAgents[0]?.agentId ?? null;

  const canGenerate = Boolean(activeAgentId);
  const canGenerateMulti =
    multi && canGenerateSelected({ selected, statuses: (cards ?? []).map((c) => c.status), isTriggering, hasAgent: canGenerate });

  const handleGenerateSelected = () => {
    onGenerate(activeAgentId || undefined, selected);
    setSelected([]); // nothing stays ticked after a run - the next one is chosen again
  };

  const handleDownload = async (kind: DrawingKind) => {
    setDownloadError(null);
    setDownloading(kind);
    try {
      await downloadDrawing(jobId, kind);
    } catch (err) {
      setDownloadError(err instanceof Error ? err.message : "Download failed.");
    } finally {
      setDownloading(null);
    }
  };



  return (
    <div className="drawing-view">
      {cards && (
        <div className="drawing-cards-intro">
          <p className="drawing-meta-text">
            Target Module: <strong>{module}</strong> • Nominal Shell ID: <strong>{shellId} mm</strong> • Engine: GstarCAD/AutoCAD Automation
          </p>
          <p className="drawing-meta-text">
            Tick the drawings to make - none are selected by default. Generation runs on <strong>your own paired machine</strong>, using your own GstarCAD.
            A drawing that is already generated can be re-generated by ticking it again; the other one can be generated later.
          </p>
          <div className="drawing-cards-grid">
            {cards.map((card) => {
              const cardGenerating = card.status === "generating";
              const ticked = selected.includes(card.kind);
              const hint = cardActionHint(card.status, ticked);
              return (
                <div key={card.kind} className={`drawing-status-card drawing-kind-card ${ticked ? "drawing-kind-card-ticked" : ""}`} data-testid={`drawing-card-${card.kind}`}>
                  <div className="drawing-status-main">
                    <div className="drawing-icon-badge">
                      <IconDrafting size={24} className="text-accent" />
                    </div>
                    <div className="drawing-info">
                      <div className="drawing-title-row">
                        <h3 className="drawing-filename">{card.label}</h3>
                        {card.status === "generated" && (
                          <span className="badge badge-status badge-completed"><IconCheckCircle size={14} /><span>Generated</span></span>
                        )}
                        {cardGenerating && (
                          <span className="badge badge-status badge-running"><IconLoader size={14} className="animate-spin" /><span>Generating...</span></span>
                        )}
                        {card.status === "failed" && (
                          <span className="badge badge-status badge-failed"><IconAlertTriangle size={14} /><span>Generation Failed</span></span>
                        )}
                        {card.status === "not_generated" && (
                          <span className="badge badge-status badge-queued"><span>Not Generated Yet</span></span>
                        )}
                      </div>
                      {card.status === "failed" && card.error && !cardGenerating && (
                        <p className="drawing-card-error" role="alert"><code>{card.error}</code></p>
                      )}
                      {hint && <p className="drawing-meta-text">{hint}</p>}
                    </div>
                  </div>
                  <div className="drawing-kind-card-actions">
                    <label className="drawing-kind-check">
                      <input
                        type="checkbox"
                        checked={ticked}
                        disabled={isGenerating}
                        onChange={(e) => setSelected((prev) => toggleDrawing(prev, card.kind, e.target.checked))}
                      />
                      <span>Generate this drawing</span>
                    </label>
                    {card.status === "generated" && (
                      <button
                        type="button"
                        className="btn btn-secondary btn-sm"
                        disabled={downloading === card.kind}
                        onClick={() => handleDownload(card.kind)}
                      >
                        {downloading === card.kind ? <IconLoader size={14} className="animate-spin" /> : <IconDrafting size={14} />}
                        <span>Download</span>
                      </button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
          {downloadError && (
            <div className="alert-banner alert-banner-danger" role="alert">
              <IconAlertTriangle size={16} />
              <span>{downloadError}</span>
            </div>
          )}
        </div>
      )}

      {/* CAD Generation Status & Action */}
      <div className="drawing-status-card">
        {!multi && <div className="drawing-status-main">
          <div className="drawing-icon-badge">
            <IconDrafting size={28} className="text-accent" />
          </div>
          <div className="drawing-info">
            <div className="drawing-title-row">
              <h3 className="drawing-filename text-mono">{jobId}</h3>
              {drawingStatus === "generated" && (
                <span className="badge badge-status badge-completed">
                  <IconCheckCircle size={14} />
                  <span>Drawing Generated</span>
                </span>
              )}
              {isGenerating && (
                <span className="badge badge-status badge-running">
                  <IconLoader size={14} className="animate-spin" />
                  <span>Generating...</span>
                </span>
              )}
              {drawingStatus === "failed" && (
                <span className="badge badge-status badge-failed">
                  <IconAlertTriangle size={14} />
                  <span>Generation Failed</span>
                </span>
              )}
              {drawingStatus === "not_generated" && !isGenerating && (
                <span className="badge badge-status badge-queued">
                  <span>Not Generated Yet</span>
                </span>
              )}
            </div>
            <p className="drawing-meta-text">
              Target Module: <strong>{module}</strong> • Nominal Shell ID:{" "}
              <strong>{shellId} mm</strong> • Engine: GstarCAD/AutoCAD Automation
            </p>
            <p className="drawing-meta-text">
              Generation runs on <strong>your own paired machine</strong>, using your own
              GstarCAD — not on the server. Select your target workstation below.
            </p>
          </div>
        </div>}

        <div className="drawing-actions">
          {onlineAgents.length > 1 && (
            <div className="workstation-picker-container">
              <span className="workstation-picker-label">CAD Machine:</span>
              <DropdownMenu.Root>
                <DropdownMenu.Trigger asChild>
                  <button
                    type="button"
                    className="workstation-single-tag workstation-dropdown-trigger"
                    disabled={isGenerating}
                  >
                    <span className="workstation-tag-name text-mono">
                      {onlineAgents.find((a) => a.agentId === activeAgentId)?.name || activeAgentId}
                    </span>
                    <span className="workstation-dropdown-caret" aria-hidden>▾</span>
                  </button>
                </DropdownMenu.Trigger>
                <DropdownMenu.Portal>
                  <DropdownMenu.Content className="workstation-dropdown-content" align="end" sideOffset={6}>
                    {onlineAgents.map((a) => (
                      <DropdownMenu.Item
                        key={a.agentId}
                        className="workstation-dropdown-item"
                        onSelect={() => setSelectedAgentId(a.agentId)}
                      >
                        <IconCheckCircle size={12} className="text-success" />
                        <span>{a.name || a.agentId}</span>
                      </DropdownMenu.Item>
                    ))}
                  </DropdownMenu.Content>
                </DropdownMenu.Portal>
              </DropdownMenu.Root>
            </div>
          )}

          {onlineAgents.length === 1 && (
            <div className="workstation-single-tag" title={`Agent ID: ${onlineAgents[0].agentId}`}>
              <span className="workstation-tag-label">Target:</span>
              <span className="workstation-tag-name text-mono">
                {onlineAgents[0].name || onlineAgents[0].agentId}
              </span>
              <span className="badge badge-status badge-completed">
                <IconCheckCircle size={10} />
                <span>Online</span>
              </span>
            </div>
          )}

          {onlineAgents.length === 0 && (
            <div className="workstation-offline-notice">
              <IconAlertTriangle size={14} className="text-amber" />
              <span>No online CAD agent</span>
            </div>
          )}

          {multi ? (
            <button
              type="button"
              className="btn btn-primary"
              onClick={handleGenerateSelected}
              disabled={!canGenerateMulti}
              title={
                !canGenerate
                  ? "Connect or start an online Local Agent below first"
                  : selected.length === 0 && !isGenerating
                    ? "Tick at least one drawing"
                    : undefined
              }
            >
              {isGenerating ? (
                <>
                  <IconLoader size={16} className="animate-spin" />
                  <span>Generating...</span>
                </>
              ) : (
                <>
                  <IconDrafting size={16} />
                  <span>Generate selected drawings</span>
                </>
              )}
            </button>
          ) : drawingStatus === "generated" ? (
            <button
              type="button"
              className="btn btn-secondary"
              onClick={() => onGenerate(activeAgentId || undefined)}
              disabled={isGenerating || !canGenerate}
              title={canGenerate ? undefined : "Connect or start an online Local Agent below first"}
            >
              <IconDrafting size={16} />
              <span>Generate Again</span>
            </button>
          ) : (
            <button
              type="button"
              className="btn btn-primary"
              onClick={() => onGenerate(activeAgentId || undefined)}
              disabled={isGenerating || !canGenerate}
              title={canGenerate ? undefined : "Connect or start an online Local Agent below first"}
            >
              {isGenerating ? (
                <>
                  <IconLoader size={16} className="animate-spin" />
                  <span>Generating...</span>
                </>
              ) : (
                <>
                  <IconDrafting size={16} />
                  <span>
                    {drawingStatus === "failed" ? "Retry Generation" : "Generate Drawing"}
                  </span>
                </>
              )}
            </button>
          )}
        </div>
      </div>

      <AgentPairingPanel
        agents={agents}
        selectedAgentId={activeAgentId}
        onSelectAgent={setSelectedAgentId}
        onRefreshAgents={loadAgents}
        isRefreshing={isFetchingAgents}
      />



      {isGenerating && (
        <div className="alert-banner alert-banner-info">
          <IconLoader size={16} className="animate-spin" />
          <span>
            CAD synthesis in progress on your paired agent's machine — a real
            GstarCAD/AutoCAD window should open there shortly. This can take over a
            minute depending on the module; the status here will update
            automatically once it finishes.
          </span>
        </div>
      )}

      {!multi && drawingStatus === "generated" && !isGenerating && (
        <div className="alert-banner alert-banner-success">
          <IconCheckCircle size={16} />
          <span>
            Drawing generated successfully. Check GstarCAD/AutoCAD on your
            paired agent's machine — the drawing was opened and left active for review.
          </span>
        </div>
      )}

      {!multi && drawingStatus === "failed" && drawingError && !isGenerating && (
        <div className="alert-banner alert-banner-danger" role="alert">
          <IconAlertTriangle size={16} />
          <span>
            Drawing generation failed: <code>{drawingError}</code>
          </span>
        </div>
      )}

    </div>
  );
}
